version: "3.8"

services:
  01factory:
    image: 01factory.io/web:latest
    build:
      context: ..
      dockerfile: ./docker/web

  db:
    image: 01factory.io/db:latest
    build:
      context: ..
      dockerfile: ./docker/postgres

  nginx:
    image: 01factory.io/nginx:latest
    build:
      context: ..
      dockerfile: ./docker/nginx
