version: "3.8"

services:
  nginx:
    image: 01factory.io/nginx:latest
    restart: unless-stopped
    environment:
      - NGINX_PORT=80
    ports:
      - 80:80
      - 443:443
    links:
      - app:webserver

  app:
    image: 01factory.io/web:latest
    restart: unless-stopped
    volumes:
      - ./data/01factory:/01factory
    links:
      - doccode:docode

  db:
    image: 01factory.io/db:latest
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql

  doccode:
    image: dfactory01-docker.pkg.coding.net/01factory/release/doccode:latest
    restart: unless-stopped
    volumes:
      - ./data/01factory:/01factory

  adminer:
    image: dfactory01-docker.pkg.coding.net/01factory/release/adminer:latest
    restart: unless-stopped

  minio:
    image: dfactory01-docker.pkg.coding.net/01factory/release/minio:latest
    restart: unless-stopped
    volumes:
      - ./data/minio:/data

  # minio1:
  #   image: dfactory01-docker.pkg.coding.net/01factory/release/minio:latest
  # restart: unless-stopped
  #   volumes:
  #     - ./data/minio11:/data1
  #     - ./data/minio12:/data2
  #   environment:
  #     - MINIO_ACCESS_KEY=mmstudio
  #     - MINIO_SECRET_KEY=mmstudio
  #   command: |
  #     server --console-address :9001 http://minio1/data1 http://minio1/data2 http://minio2/data1 http://minio2/data2

  # minio2:
  #   image: dfactory01-docker.pkg.coding.net/01factory/release/minio:latest
  # restart: unless-stopped
  #   volumes:
  #     - ./data/minio21:/data1
  #     - ./data/minio22:/data2
  #   environment:
  #     - MINIO_ACCESS_KEY=mmstudio
  #     - MINIO_SECRET_KEY=mmstudio
  #   command: |
  #     server --console-address :9001 http://minio1/data1 http://minio1/data2 http://minio2/data1 http://minio2/data2

  mc:
    stdin_open: true
    tty: true
    image: dfactory01-docker.pkg.coding.net/01factory/release/mc:latest
    restart: unless-stopped
    volumes:
      - ./data/mc:/root/.mc
      - ./data/files:/01factory

  fileview:
    image: dfactory01-docker.pkg.coding.net/01factory/release/fileview:latest
    restart: unless-stopped
    volumes:
      - ./data/01factory:/01factory
    links:
      - app:webserver
