export default {
	'/': '/01factory',
	'/Vector 1.svg': '/01factory/Vector 1.svg',
	'/favicon-16x16.ico': '/01factory/favicon-16x16.ico',
	'/favicon-32x32.ico': '/01factory/favicon-32x32.ico',
	'/favicon.ico': '/01factory/favicon.ico',
	'/images/add.png': '/01factory/images/add.png',
	'/images/captcha/captcha1.jpg': '/01factory/images/captcha/captcha1.jpg',
	'/images/captcha/captcha2.png': '/01factory/images/captcha/captcha2.png',
	'/images/card02.png': '/01factory/images/card02.png',
	'/images/del.svg': '/01factory/images/del.svg',
	'/images/fileadd.png': '/01factory/images/fileadd.png',
	'/images/fileadd.svg': '/01factory/images/fileadd.svg',
	'/images/h5/5.png': '/01factory/images/h5/5.png',
	'/images/h5/Avatar 1.png': '/01factory/images/h5/Avatar 1.png',
	'/images/h5/logo3.svg': '/01factory/images/h5/logo3.svg',
	'/images/h5/nav.png': '/01factory/images/h5/nav.png',
	'/images/h5/search-normal.png': '/01factory/images/h5/search-normal.png',
	'/images/h5/search-normal.svg': '/01factory/images/h5/search-normal.svg',
	'/images/h5/settings.png': '/01factory/images/h5/settings.png',
	'/images/h5/settings.svg': '/01factory/images/h5/settings.svg',
	'/images/h5/touxiang.svg': '/01factory/images/h5/touxiang.svg',
	'/images/item_img.svg': '/01factory/images/item_img.svg',
	'/images/logo3 1.svg': '/01factory/images/logo3 1.svg',
	'/images/logo3.svg': '/01factory/images/logo3.svg',
	'/images/sys/acc.png': '/01factory/images/sys/acc.png',
	'/images/sys/acc1.png': '/01factory/images/sys/acc1.png',
	'/images/sys/avatar.png': '/01factory/images/sys/avatar.png',
	'/images/sys/bgimg.png': '/01factory/images/sys/bgimg.png',
	'/images/sys/del.png': '/01factory/images/sys/del.png',
	'/images/sys/del2.png': '/01factory/images/sys/del2.png',
	'/images/sys/group.svg': '/01factory/images/sys/group.svg',
	'/images/sys/homelogo.png': '/01factory/images/sys/homelogo.png',
	'/images/sys/logout.png': '/01factory/images/sys/logout.png',
	'/images/sys/mima.png': '/01factory/images/sys/mima.png',
	'/images/sys/mima1.png': '/01factory/images/sys/mima1.png',
	'/images/sys/norole.png': '/01factory/images/sys/norole.png',
	'/images/sys/repass.png': '/01factory/images/sys/repass.png',
	'/images/sys/role.svg': '/01factory/images/sys/role.svg',
	'/images/sys/rolecard.png': '/01factory/images/sys/rolecard.png',
	'/images/sys/rolecard1.png': '/01factory/images/sys/rolecard1.png',
	'/images/sys/setting.png': '/01factory/images/sys/setting.png',
	'/images/sys/switchuser.png': '/01factory/images/sys/switchuser.png',
	'/images/sys/upload.svg': '/01factory/images/sys/upload.svg',
	'/images/sys/user-role.png': '/01factory/images/sys/user-role.png',
	'/images/sys/user.svg': '/01factory/images/sys/user.svg',
	'/images/sys/yonghu.png': '/01factory/images/sys/yonghu.png',
	'/images/top.svg': '/01factory/images/top.svg',
	'/images/zhmtzh.svg': '/01factory/images/zhmtzh.svg',
	'/shoubianwz.svg': '/01factory/shoubianwz.svg',
	'/shouji.svg': '/01factory/shouji.svg',
	'/shoujiwenzi.svg': '/01factory/shoujiwenzi.svg',
	'/touxiang.jpg': '/01factory/touxiang.jpg',
	'/vercel.svg': '/01factory/vercel.svg',
	'/wenzi1.svg': '/01factory/wenzi1.svg',
	'/xinzeng.png': '/01factory/xinzeng.png',
	'/yaoshi.jpg': '/01factory/yaoshi.jpg'
};
